# Generated by Django 6.0.3 on 2026-07-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineuser',
            name='connections',
            field=models.IntegerField(default=0),
        ),
    ]
